name: Copper Hill

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Copper Hill self-hosted Linux runner!
        run: uname -a
